language:
  - cpp

sudo: required

compiler:
  - clang
  - gcc

os:
  - linux
#  - osx

env:
  - CMAKE_BUILD_TYPE=Release
  - CMAKE_BUILD_TYPE=Debug

addons:
  apt:
    packages:
    - valgrind

install:
  - sudo pip install cpp-coveralls
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install valgrind; fi

script:
  - mkdir Build
  - cd Build
  - cmake ..
  - make
  - valgrind --leak-check=yes ctest --output-on-failure

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
